### ISSUE TITLE
.Catch not appearing in intellisense and not accepted in Visual Studio

### ISSUE THREAD

**Issue by rmast** [procudin/catchable-enumerable#1]
Hi,

I tried to use your CatchableEnumerable in some (.Net 4.7.2)-code. I included the project in the solution.
The .AsCatchable appeared in the intellisense for the first IEnumerable I tried it on, but I couldn't find a spot in the following chain where the .Catch would be accepted.

I saw a lot of the classes are defined as "internal", but even with removing that predicate the .Catch wouldn't show up.

Finally I decided just to follow the extended try-catch sentence you tried to solve. The only reason I want this is to be able to debug a large Linq-statement for which the only line-number in the exception that pops up is the first line of the complete statement. I hope using 'throw' in the catch would give me the right linenumber.

**Comment by procudin** [comment]
Hi!
AsCatchable moves IEnumerable to catchable context (returns object of ICatchableEnumerable). I've implemented some linq overloads (now Select and Where only), which works with this interface and also retuns ICatchableEnumerable. Finaly you can use Catch method, which also works with ICatchableEnumerable only. 

I've created small examle: https://dotnetfiddle.net/8a559C . If you still have any troubles, you can also create your example and paste here. 

There is existed bug with intellisense, that i've found while creating this example. It's about is incorrect linq operation suggestion.   When i'm trying to write ".Select" it's suggedted me default IEnumerable extention except of ICatchableEnumerable. But after completion of method creating, it's displayed my method.

**Comment by procudin** [comment]
I've just added some examples to readme
